<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Purchase Invoice #{{ $purchase->invoice_number }}</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
    .header { background: #1a5276; color: #fff; padding: 20px; margin-bottom: 20px; }
    .header h1 { font-size: 22px; margin-bottom: 4px; }
    .header p { font-size: 11px; opacity: 0.8; }
    .info-row { display: table; width: 100%; margin-bottom: 20px; }
    .info-col { display: table-cell; width: 50%; vertical-align: top; padding: 0 10px 0 0; }
    .info-col:last-child { padding: 0 0 0 10px; text-align: right; }
    .info-col h3 { font-size: 13px; border-bottom: 2px solid #1a5276; padding-bottom: 4px; margin-bottom: 8px; }
    .info-col p { line-height: 1.8; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    table th { background: #1a5276; color: #fff; padding: 8px 10px; text-align: left; font-size: 11px; }
    table td { padding: 7px 10px; border-bottom: 1px solid #e0e0e0; font-size: 11px; }
    table tr:nth-child(even) td { background: #f9f9f9; }
    .totals { width: 50%; margin-left: auto; border-collapse: collapse; }
    .totals td { padding: 6px 10px; }
    .totals td:first-child { font-weight: bold; }
    .totals tr:last-child td { background: #1a5276; color: #fff; font-weight: bold; font-size: 13px; }
    .footer { text-align: center; margin-top: 30px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head>
<body>

<div class="header">
    <h1>{{ $setting->company_name ?? 'POS System' }}</h1>
    <p>PURCHASE INVOICE</p>
</div>

<div class="info-row">
    <div class="info-col">
        <h3>Supplier Information</h3>
        <p>
            <strong>Name:</strong> {{ $purchase->supplier->name ?? 'N/A' }}<br>
            <strong>Email:</strong> {{ $purchase->supplier->email ?? '-' }}<br>
            <strong>Phone:</strong> {{ $purchase->supplier->phone ?? '-' }}
        </p>
    </div>
    <div class="info-col">
        <h3>Purchase Details</h3>
        <p>
            <strong>Invoice No:</strong> {{ $purchase->invoice_number }}<br>
            <strong>Date:</strong> {{ \Carbon\Carbon::parse($purchase->purchase_date)->format('d M Y') }}<br>
            <strong>Warehouse:</strong> {{ $purchase->warehouse->name ?? '-' }}<br>
            <strong>Branch:</strong> {{ $purchase->branch->name ?? '-' }}
        </p>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Product</th>
            <th>Variant</th>
            <th>Qty</th>
            <th>Unit Cost</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($purchase->items as $i => $item)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td>{{ $item->product->name ?? 'N/A' }}</td>
            <td>{{ $item->variant->variant_name ?? '-' }}</td>
            <td>{{ $item->quantity }} {{ $item->unit->name ?? '' }}</td>
            <td>{{ $currencySymbol }} {{ number_format($item->unit_cost, 2) }}</td>
            <td>{{ $currencySymbol }} {{ number_format($item->total_cost, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<table class="totals">
    @if(isset($purchase->discount_amount) && $purchase->discount_amount > 0)
    <tr>
        <td>Discount:</td>
        <td>- {{ $currencySymbol }} {{ number_format($purchase->discount_amount, 2) }}</td>
    </tr>
    @endif
    @if(isset($purchase->tax_amount) && $purchase->tax_amount > 0)
    <tr>
        <td>Tax:</td>
        <td>{{ $currencySymbol }} {{ number_format($purchase->tax_amount, 2) }}</td>
    </tr>
    @endif
    <tr>
        <td>Grand Total:</td>
        <td>{{ $currencySymbol }} {{ number_format($purchase->total_amount, 2) }}</td>
    </tr>
</table>

<div class="footer">
    <p>Generated by {{ $setting->company_name ?? 'POS System' }}</p>
</div>

</body>
</html>
