<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Low Stock Alert</title>
<style>
    body { font-family: Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    .header { background: #e74c3c; color: #fff; padding: 24px; text-align: center; }
    .header h1 { margin: 0; font-size: 22px; }
    .header p { margin: 6px 0 0; font-size: 13px; opacity: 0.9; }
    .body { padding: 24px; }
    .body p { color: #555; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th { background: #f4f4f4; color: #333; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 13px; color: #444; }
    .badge-danger { background: #e74c3c; color: #fff; border-radius: 12px; padding: 2px 10px; font-size: 11px; }
    .footer { background: #f9f9f9; padding: 16px 24px; text-align: center; font-size: 11px; color: #aaa; border-top: 1px solid #eee; }
</style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>&#9888; Low Stock Alert</h1>
            <p>The following products have reached or fallen below their minimum stock threshold.</p>
        </div>
        <div class="body">
            <p>Hello Admin,</p>
            <p>This is an automated alert. The following <strong>{{ $products->count() }} product(s)</strong> are running low on stock and require your attention:</p>

            <table>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>SKU</th>
                        <th>Current Stock</th>
                        <th>Threshold</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                    <tr>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->sku ?? '-' }}</td>
                        <td><span class="badge-danger">{{ $product->total_stock ?? 0 }}</span></td>
                        <td>{{ $product->low_stock ?? 5 }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            <p style="margin-top: 20px;">Please restock these products as soon as possible to avoid disruptions.</p>
        </div>
        <div class="footer">
            This email was automatically generated by the POS System. Please do not reply to this email.
        </div>
    </div>
</body>
</html>
